# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_merch', models.CharField(max_length=50)),
                ('merch_price', models.CharField(blank=True, default=b'', max_length=100)),
                ('merch_count', models.CharField(max_length=100)),
                ('merch_enabled', models.CharField(max_length=1)),
                ('merch_del', models.CharField(max_length=1)),
                ('image', models.FilePathField(blank=True, null=True)),
                ('merch_description', models.TextField(blank=True, default=b'')),
            ],
            options={
                'db_table': 'order_merch_cat',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField()),
                ('order_description', models.TextField(blank=True, default=b'')),
                ('order_state', models.CharField(max_length=1)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_info',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merch_sum', models.CharField(max_length=100)),
                ('order_price', models.CharField(max_length=100)),
                ('merch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderbase.Merchandise')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderbase.Order')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_login', models.CharField(max_length=100)),
                ('user_password', models.CharField(blank=True, default=b'', max_length=100)),
            ],
            options={
                'db_table': 'users_order',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderbase.Users'),
        ),
    ]
