# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbase', '0002_auto_20161012_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='merch_del',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='merch_enabled',
            field=models.BooleanField(default=1),
        ),
    ]
