# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderbase', '0004_auto_20161124_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='loaded',
        ),
        migrations.AddField(
            model_name='photo',
            name='merch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderbase.Merchandise'),
        ),
    ]
